server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/board
#    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

#spring:
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      use-new-id-generate-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#  thymeleaf:
#    cache: false